export enum ALObjectType {
    codeunit = "codeunit",
    enum = "enum",
    enumextension = "enumextension",
    page = "page",
    pageextension = "pageextension",
    permissionset = "permissionset",
    permissionsetextension = "permissionsetextension",
    query = "query",
    report = "report",
    reportextension = "reportextension",
    table = "table",
    tableextension = "tableextension",
    xmlport = "xmlport",
}
