### Localhost - POST

post http://localhost:7071/api/v1/syncIds
Content-Type: application/json

{
    "appId": "3a4a7e9d73ca881f8708427acf6754bf69c4a7f22a2c991400823838218888cf",
    "ids": {
        "codeunit": [1, 2, 3]
    } 
}


### Localhost - PATCH

patch http://localhost:7071/api/v1/syncIds
Content-Type: application/json

{
    "appId": "3a4a7e9d73ca881f8708427acf6754bf69c4a7f22a2c991400823838218888cf",
    "ids": {
        "codeunit": [4,5]
    } 
}


### Remote

post https://vjekocom-alext-weu.azurewebsites.net/api/v1/syncIds
Content-Type: application/json

{
    "appId": "c454e488-56ca-4414-bd68-1d3a2548abf2",
    "ids": {
        "codeunit": [50000,50001]
    }
}
