### Localhost - GET

get http://localhost:7071/api/v1/getNext?blabla=4
Content-Type: application/json
X-Forwarded-For: 192.168.0.23

{
    "appId": "83b9edea7c8a47f8e2307dca527994e7e4d154254839c48f02c4936e89a3fa62",
    "authKey": "UMA7rdzunEWhpzYXRGNJIcK5Zt/PA4nrwDRlnmcqf04=",
    "type": "codeunit",
    "ranges": [
        {
            "from": 50100,
            "to": 59999
        }
    ]
}


### Localhost - POST

post http://localhost:7071/api/v1/getNext
Content-Type: application/json

{
    "appId": "83b9edea7c8a47f8e2307dca527994e7e4d154254839c48f02c4936e89a3fa62",
    "authKey": "UMA7rdzunEWhpzYXRGNJIcK5Zt/PA4nrwDRlnmcqf04=",
    "type": "codeunit",
    "ranges": [
        {
            "from": 50100,
            "to": 59999
        }
    ],
    "content": {
        "user": "waldo"
    }
}


### Remote

post https://vjekocom-alext-weu-2.azurewebsites.net/api/v1/getnext
Content-Type: application/json

{
    "appId": "08434c1c977f16b0901157a44860fbb2c70d6e0e7fe488d05aeed14724390e46",
    "type": "codeunit",
    "ranges": [
        {
            "from": 50130,
            "to": 50199
        }
    ],
    "content": {
        "user": "waldo"
    }
}
