### Localhost - post

post http://localhost:7071/api/v2/authorizeApp
Content-Type: application/json

{
    "appId": "0_test",
    "gitUser": "Vjeko",
    "gitEMail": "vjeko@vjeko.com"
}

### Localhost - get

get http://localhost:7071/api/v2/authorizeApp
Content-Type: application/json

{
    "appId": "0_test"
}

### Localhost - delete

delete http://localhost:7071/api/v2/authorizeApp
Content-Type: application/json

{
    "appId": "0_test",
    "authKey": "h1ghP+SFaOrL0NE63HuvMzKPgkmPtjNlg4W2SG9+ta0="
}

### Azure

get https://vjekocom-alext-weu.azurewebsites.net/api/v2/authorizeApp
Content-Type: application/json

{
    "appId": "0_test"
}
