post http://localhost:7071/api/telemetry
Content-Type: application/json

{
    "userSha": "cscscs",
    "appSha": "babebt",
    "event": "start",
    "context": {
        "vscode": "1.68.0",
        "ninja": "2.9.2"
    }
}
