### Localhost - POST

post http://localhost:7071/api/v1/syncIds
Content-Type: application/json

{
    "appId": "3a4a7e9d73ca881f8708427acf6754bf69c4a7f22a2c991400823838218888cf",
    "ids": {
        "codeunit": [1, 2, 3]
    } 
}


### Localhost - PATCH

patch http://localhost:7071/api/v1/syncIds
Content-Type: application/json

{
    "appId": "3a4a7e9d73ca881f8708427acf6754bf69c4a7f22a2c991400823838218888cf",
    "ids": {
        "codeunit": [4,5]
    } 
}


### Remote

patch https://vjekocom-alext-weu.azurewebsites.net/api/v1/syncIds
Content-Type: application/json

{
    "appId": "ea950ccb54c7704405a46c9d9eddc05682a4c780c5e2900f69303bf0e4786379",
    "ids": {
        "codeunit": [50000,50001]
    }
}
