### Localhost

get http://localhost:7071/api/v2/getLog
Content-Type: application/json
X-Forwarded-For: 192.168.0.23

{
    "appFolders": [
        {
            "appId": "83b9edea7c8a47f8e2307dca527994e7e4d154254839c48f02c4936e89a3fa62",
            "authKey": "zVBD2a9W6s17fXwMnLBInzVCP+qklPd69W6DLXqQZI0="
        },
        {
            "appId": "08434c1c977f16b0901157a44860fbb2c70d6e0e7fe488d05aeed14724390e46"
        }
    ]
}

### Azure

get https://vjekocom-alext-weu.azurewebsites.net/api/v2/getLog
Content-Type: application/json

{
    "appFolders": [
        {
            "appId": "83b9edea7c8a47f8e2307dca527994e7e4d154254839c48f02c4936e89a3fa62"
        },
        {
            "appId": "08434c1c977f16b0901157a44860fbb2c70d6e0e7fe488d05aeed14724390e46"
        }
    ]
}
