### Localhost

get http://localhost:7071/api/v1/getLog
Content-Type: application/json

{
    "appId": "86b923bb85a2958b584a36a47a107f91238747f5938dc41872be4ee5c4ef36c3",
    "authKey": "eG9jUknPMqbtHq72kObF1E803Az642px8VNkl6Voxio="
}

### Azure

get https://vjekocom-alext-weu.azurewebsites.net/api/v1/getLog
