# Get localhost

post http://localhost:7071/api/v2/getNext
Content-Type: application/json

{
    "appId": "0_test",
    "type": "codeunit",
    "ranges": [
        {
            "from": 90000,
            "to": 90150
        }
    ],
    "count": 1,
    "fromRange": {
        "from": 90000,
        "to": 90150
    }
}
