### Localhost - post

post http://localhost:7071/api/v1/authorizeApp
Content-Type: application/json

{
    "appId": "83b9edea7c8a47f8e2307dca527994e7e4d154254839c48f02c4936e89a3fa62"
}

### Localhost - delete

delete http://localhost:7071/api/v1/authorizeApp
Content-Type: application/json

{
    "appId": "83b9edea7c8a47f8e2307dca527994e7e4d154254839c48f02c4936e89a3fa62",
    "authKey": "zVBD2a9W6s17fXwMnLBInzVCP+qklPd69W6DLXqQZI0="
}

### Azure

post https://vjekocom-alext-weu.azurewebsites.net/api/v1/authorizeApp
Content-Type: application/json

{
    "appId": "c454e488-56ca-4414-bd68-1d3a2548abf2"
}
