### Localhost

post http://localhost:7071/api/v1/authorizeApp
Content-Type: application/json

{
    "appId": "67295cd84-95f4-4313-9d3c-a5a6e8d8c15a",
    "key": "O9VSwP1RfhsievUHDB3HQVFin0N6rdXSkx7ct2wvAbw="
}
