### Localhost

post http://localhost:7071/api/v1/getNext
Content-Type: application/json

{
    "appId": "eea13c88-1ff5-4fcd-b450-70468fa84d5d",
    "type": "codeunit",
    "ranges": [
        {
            "from": 50111,
            "to": 50115
        },
        {
            "from": 50100,
            "to": 50105
        },
        {
            "from": 50120,
            "to": 50125
        }
    ],
    "authKey": "anwUaXOeSGhR6SSFJ8Xx33nKzpZgUsE2BzpGLOhNrQc=",
    "content": {
        "user": "clovio\\vjeko"
    }
}


### Remote

post https://vjekocom-alext-weu.azurewebsites.net/api/v1/getnext
Content-Type: application/json

{
    "appId": "67295c84-95f4-4313-9d3c-a5a6e8d8c15a",
    "type": "codeunit",
    "authKey": "K6cJc/Z+e3A1x6ibgGmzDxjOKv8ZkyPrnzXFej1Q4Ic=",
    "ranges": [
        {
            "from": 50111,
            "to": 50115
        },
        {
            "from": 50100,
            "to": 50105
        },
        {
            "from": 50120,
            "to": 50125
        }
    ],
    "content": {
        "user": "waldo"
    }
}
