### Request a new public key

get http://localhost:7071/api/v2/getPoolInfo
Content-Type: application/json

{
    "poolId": "ba320dfe086b2e139c37ff83f4535ab9a6f7ba6c452565e0aa8a5d0e9d2e5777",
    "accessKey": "4d4eqDs1+Fx53iqwO4IHLXpEHIu6RfeZ"
}
